[apidocs] NoSuchMethodError with latest JDT due to internal API changes
Bug: 459519
Change-Id: If873609619cf150ff151122e9c1fd63625be34b9
Signed-off-by: Andreas Sewe <andreas.sewe@codetrails.com>